version: "3"
services:
  kernel:
    image: sh39sxn/aion-kernel:latest
    env_file:
     -  ./aion-kernel.env
    ports:
     - "8545:8545"
  solo-mining-pool:
    image: sh39sxn/aion-solo-mining-pool:latest
    env_file:
     -  ./aion-solo-mining-pool.env
    ports:
     - "3333:3333"
    links:
     - kernel
     - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  cpu-miner:
    image: sh39sxn/aion-miner-cpu:latest
    env_file:
     -  ./aion-cpu-miner.env
    links:
     -  solo-mining-pool
  gpu-miner:
    image: sh39sxn/aion-miner-gpu:latest
    env_file:
     -  ./aion-gpu-miner.env
    links:
     -  solo-mining-pool